name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push]
jobs:
  lucifer-validation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: |
          pip install numpy
          make
          HERE=$(pwd)
          ln -s $HERE/lucipy.cpython-310-x86_64-linux-gnu.so $HERE/test/lucipy.cpython-310-x86_64-linux-gnu.so
          ls -al $HERE/test
          ./test/testLucif77.exe
          python ./test/testLucipy.py
